#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e
[ -z "${DEBUG}" ] || set -x

BASEDIR="$(dirname "$0")/.."
cd "${BASEDIR}"

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update; brew bundle check >/dev/null 2>&1 || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle
  }
fi

echo "One for the money"
